spring:
  cloud:
    config:
      server:
        svn:
          uri: http://svncloud.it.taikang.com/svn/SourceCode/health/hie/cust/branches/demo/config-server
          username: zhanghb22
          password: zhanghb2266
      enabled: true
  profiles:
    active: subversion
eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/